#!/usr/bin/env python3
"""Generate the reference documentation that has a single source of truth.

``docs/using/diagnostics.md`` is rendered from the diagnostic catalog and
``docs/developing/crosswalk.md`` from the mapping files. Both are pure
restatements of data that already exists in the code, so writing them by hand
would only create two things to keep in step. CI runs this script in
``--check`` mode, which means a rule added without regenerating the docs fails
the build rather than shipping undocumented.

Usage::

    poetry run python scripts/generate_docs.py
    poetry run python scripts/generate_docs.py --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from rs_metadata.adapters import ADAPTERS, ANCHOR, Adapter, companion_adapters
from rs_metadata.diagnostics import CATALOG, Namespace, Severity
from rs_metadata.mapping import Origin, available, load

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "rs_metadata"

DOCS = ROOT / "docs"


def module_map() -> list[str]:
    """The package layout, with each part's own one-line summary.

    Read from the packages themselves rather than kept in prose, so a new
    subpackage appears here by existing and a renamed one cannot leave a stale
    entry behind.
    """
    import ast

    rows: list[tuple[str, str]] = []
    for init in sorted(SRC.rglob("__init__.py")):
        package = init.parent
        if package == SRC or "__pycache__" in str(package):
            continue
        doc = ast.get_docstring(ast.parse(init.read_text(encoding="utf-8"))) or ""
        summary = doc.strip().split("\n", 1)[0] if doc else ""
        rows.append((f"`{package.relative_to(SRC)}/`", summary))

    for module in sorted(SRC.glob("*.py")):
        if module.name.startswith("_"):
            continue
        doc = ast.get_docstring(ast.parse(module.read_text(encoding="utf-8"))) or ""
        summary = doc.strip().split("\n", 1)[0] if doc else ""
        rows.append((f"`{module.name}`", summary))

    width = max(len(name) for name, _ in rows)
    lines = [f"| {'Module':<{width}} | Holds |", f"|{'-' * (width + 2)}|---|"]
    lines += [f"| {name:<{width}} | {summary} |" for name, summary in rows]
    return lines


BANNER = (
    "<!-- Generated by scripts/generate_docs.py. Do not edit by hand; run the "
    "script instead. -->"
)


def diagnostics_page() -> str:
    lines = [
        "# Diagnostics",
        "",
        BANNER,
        "",
        "**For anyone maintaining research software.** What each",
        "finding means and how to resolve it.",
        "",
        "Every finding rs-metadata reports carries one of the codes below.",
        "Codes are a public interface: within a major version a code never",
        "changes meaning, so it is safe to filter on one, link to one, or key",
        "an editor integration off one.",
        "",
        "Run `rs-metadata explain <code>` for the same information in a",
        "terminal.",
        "",
        "## Severity",
        "",
        "| Severity | Meaning |",
        "|---|---|",
        *(f"| `{level.value}` | {level.meaning} |" for level in Severity),
        "",
        "Severity is a property of the finding. Turning a severity into a build",
        "failure is policy, controlled by `--fail-on` — the same report can",
        "drive a strict institutional gate and a lenient local check.",
        "",
        "## Index",
        "",
        "| Code | Severity | Summary |",
        "|---|---|---|",
    ]
    for code in sorted(CATALOG):
        entry = CATALOG[code]
        anchor = code.replace(".", "")
        lines.append(
            f"| [`{code}`](#{anchor}) | `{entry.severity.value}` | {entry.title} |"
        )

    for namespace in Namespace:
        codes = sorted(c for c in CATALOG if c.startswith(f"{namespace}."))
        if not codes:
            continue
        lines += ["", f"## {namespace.heading}", "", namespace.description, ""]
        for code in codes:
            entry = CATALOG[code]
            lines += [
                f"### {code}",
                "",
                f"**{entry.title}** — reported at `{entry.severity.value}` at most.",
                "",
                " ".join(entry.description.split()),
                "",
            ]
            if entry.remediation:
                lines += [
                    "*How to resolve it.* " + " ".join(entry.remediation.split()),
                    "",
                ]
    return "\n".join(lines).rstrip() + "\n"


def crosswalk_page() -> str:
    lines = [
        "# Crosswalk reference",
        "",
        BANNER,
        "",
        "Which CodeMeta concept each supported format maps onto, how strictly",
        "the two are expected to agree, and where the mapping came from.",
        "",
        "See [consistency.md](consistency.md) for the model behind these",
        "tables, and [adapters.md](adapters.md) for how to add a format.",
        "",
        "This is developer reference. If you are here because a",
        "consistency check failed, [diagnostics](../using/diagnostics.md)",
        "and the [FAQ](../using/faq.md) are the faster route.",
        "",
        "## Comparison rules",
        "",
        "| Rule | Violated when |",
        "|---|---|",
        "| `equal` | The two sides are not equivalent in either direction. |",
        "| `subset` | The source holds a value the anchor does not. The "
        "reverse is fine: `codemeta.json` is allowed to be richer. |",
        "| `overlap` | The two sides have nothing in common at all. |",
        "| `informational` | Never. Differences are reported without judgement. |",
        "",
        "## Mapping provenance",
        "",
        "| Origin | Meaning |",
        "|---|---|",
        "| `codemeta-upstream` | Taken from the CodeMeta project's own "
        "crosswalk tables. |",
        "| `mixed` | Based on an upstream crosswalk and extended here. |",
        "| `rs-metadata` | Defined here, because no adequate upstream "
        "mapping exists. |",
        "",
        "Provenance travels with every consistency finding in the JSON report,",
        "so a reader can always tell which kind of mapping produced it.",
    ]

    for name in available():
        mapping = load(name)
        reference = mapping.reference
        lines += [
            "",
            f"## {mapping.format}",
            "",
            f"- **Mapping id:** `{mapping.id}`",
            f"- **Format version:** {mapping.format_version or 'unversioned'}",
            f"- **Provenance:** {Origin(reference.origin).label}",
        ]
        if reference.source:
            lines.append(f"- **Upstream table:** <{reference.source}>")
        if reference.retrieved:
            lines.append(f"- **Retrieved:** {reference.retrieved}")
        if mapping.notes:
            lines += ["", " ".join(mapping.notes.split())]
        lines += [
            "",
            "| CodeMeta concept | Source field | Comparison | Rule | Severity |",
            "|---|---|---|---|---|",
        ]
        for concept in sorted(mapping.fields):
            rule = mapping.fields[concept]
            if not rule.comparable:
                lines.append(
                    f"| `{concept}` | `{rule.source}` | — | not comparable | — |"
                )
            else:
                lines.append(
                    f"| `{concept}` | `{rule.source}` | `{rule.strategy}` | "
                    f"{rule.rule.label} | `{rule.severity.value}` |"
                )

        notes = [
            (concept, mapping.fields[concept])
            for concept in sorted(mapping.fields)
            if mapping.fields[concept].note or mapping.fields[concept].reason
        ]
        if notes:
            lines += ["", "**Notes**", ""]
            for concept, rule in notes:
                text = " ".join((rule.note or rule.reason or "").split())
                lines.append(f"- `{concept}` — {text}")
    return "\n".join(lines).rstrip() + "\n"


#: Output path relative to docs/, paired with the function that renders it.
PAGES = {
    "using/diagnostics.md": diagnostics_page,
    "developing/crosswalk.md": crosswalk_page,
}


#: A page that is hand-written apart from one generated block, marked by these
#: lines. Substituting rather than rendering keeps the prose editable.
MODULE_MAP_START = (
    "<!-- Generated by scripts/generate_docs.py from each module's own docstring. -->"
)
MODULE_MAP_END = "## Key types"


def architecture_with_module_map() -> str:
    """``architecture.md`` with its module map refreshed from the source."""
    path = DOCS / "developing" / "architecture.md"
    text = path.read_text(encoding="utf-8")
    start = text.index(MODULE_MAP_START) + len(MODULE_MAP_START)
    end = text.index(MODULE_MAP_END)
    return text[:start] + "\n\n" + "\n".join(module_map()) + "\n\n" + text[end:]


#: How many nodes to chain per invisible-link row in the sources diagram.
_DIAGRAM_ROW = 5

SOURCES_START = (
    "<!-- Generated by scripts/generate_docs.py from the adapter registry. -->"
)
SOURCES_END = "Comparison is semantic."


def sources_block() -> list[str]:
    """The supported formats, as a diagram and a table, read from the registry.

    Kept generated rather than written out so that registering an adapter is
    the only step: a format cannot be supported but undocumented, and a
    renamed one cannot leave a stale row behind.
    """

    companions = list(companion_adapters())

    def node(adapter: Adapter, key: str, first: bool) -> str:
        # The hub is declared on the first edge rather than on a line of its
        # own, so mermaid places it between the two rows instead of after
        # them.
        hub = "N([normalized CodeMeta concepts]):::mid" if first else "N"
        return f"    {key}[{adapter.filenames[0]}]:::src --> {hub}"

    lines = ["```mermaid", "flowchart LR"]
    lines += [node(a, f"S{i}", i == 0) for i, a in enumerate(companions)]
    lines += [
        f"    CM[{ANCHOR.filenames[0]}<br/><i>anchor</i>]:::anchor --> N",
        "",
    ]
    # Invisible links, which mermaid uses for ordering without drawing
    # anything. Without them the sources stack into one tall column; chained
    # in fives they lay out as rows, which is what makes the diagram readable
    # at the width of a README.
    keys = [f"S{i}" for i in range(len(companions))] + ["CM"]
    lines += [
        "    " + " ~~~ ".join(keys[start : start + _DIAGRAM_ROW])
        for start in range(0, len(keys), _DIAGRAM_ROW)
    ]
    lines += [
        "",
        "    classDef src fill:#eef4fb,stroke:#5b8db8",
        "    classDef anchor fill:#fdf1e2,stroke:#c98b34",
        "    classDef mid fill:#f2f2f2,stroke:#888",
        "```",
        "",
        "| Source | Detected as | Required |",
        "|---|---|---|",
    ]
    required = {"anchor": "anchor", "required": "yes", "optional": "auto-detected"}
    for adapter in ADAPTERS:
        names = " / ".join(f"`{name}`" for name in adapter.filenames)
        lines.append(f"| {adapter.format} | {names} | {required[adapter.role]} |")
    return lines


def readme_with_sources() -> str:
    """``README.md`` with its supported-format block refreshed from the registry."""
    path = ROOT / "README.md"
    text = path.read_text(encoding="utf-8")
    start = text.index(SOURCES_START) + len(SOURCES_START)
    end = text.index(SOURCES_END)
    return text[:start] + "\n\n" + "\n".join(sources_block()) + "\n\n" + text[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated pages differ from what is committed",
    )
    args = parser.parse_args()

    stale = []
    partials = {
        "developing/architecture.md": architecture_with_module_map,
        "../README.md": readme_with_sources,
    }
    for name, render in {**PAGES, **partials}.items():
        path = (DOCS / name).resolve()
        path.parent.mkdir(parents=True, exist_ok=True)
        content = render()
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"  wrote {path.relative_to(ROOT)}")

    if args.check and stale:
        print(f"\nOut of date: {', '.join(stale)}", file=sys.stderr)
        print("Run: poetry run python scripts/generate_docs.py", file=sys.stderr)
        return 1
    if args.check:
        print("Generated documentation is up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
