"""The center of the vendoring script: what gets built, from what.

Each vendored file is one :class:`Artifact`, declaring the sources it derives
from and the function that derives it. Everything else follows from that
declaration. ``provenance.json`` in particular is computed by inverting it, so
the ``files`` listed under a source are the files that source actually
contributed to, rather than a second list somebody has to keep in step.
"""

from __future__ import annotations

import datetime as dt
import json
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import codemeta, crosswalks, hints, licenses, schemaorg, vocabularies
from .sources import SOURCES, Download, fetch_all

DATA_DIR = Path(__file__).resolve().parents[2] / "src" / "rs_metadata" / "data"

Downloads = dict[str, Download]


@dataclass(frozen=True)
class Artifact:
    """One file written into ``src/rs_metadata/data``."""

    name: str
    #: Keys into :data:`~vendoring.sources.SOURCES`. Recorded in provenance,
    #: so a stale upstream can be traced to every file it touched.
    sources: tuple[str, ...]
    build: Callable[[Downloads], Any]


def _types(downloads: Downloads) -> dict[str, Any]:
    """CodeMeta's property table, backfilled from schema.org where it is silent."""
    document = downloads["schema-org"].json
    classes = schemaorg.schema_org_classes(document, set())["classes"]
    return schemaorg.merge_types(
        codemeta.build_codemeta_types(
            downloads["codemeta-properties"].text, schemaorg.document_parents(classes)
        ),
        schemaorg.schema_org_ranges(document),
        codemeta.term_iris(downloads["codemeta"].json),
    )


def _classes(downloads: Downloads) -> dict[str, Any]:
    """The class hierarchy, detailed for exactly the classes the types reach."""
    reachable = {
        name
        for entry in _types(downloads)["properties"].values()
        for name in entry["range"]
    }
    return schemaorg.schema_org_classes(downloads["schema-org"].json, reachable)


ARTIFACTS: tuple[Artifact, ...] = (
    Artifact(
        "codemeta-3.1-context.jsonld",
        ("codemeta",),
        lambda d: d["codemeta"].json,
    ),
    Artifact(
        "codemeta-3.1-terms.json",
        ("codemeta",),
        lambda d: codemeta.build_codemeta_terms(d["codemeta"].json),
    ),
    Artifact(
        "codemeta-3.1-types.json",
        ("codemeta", "codemeta-properties", "schema-org"),
        _types,
    ),
    Artifact(
        "schema-org-classes.json",
        ("schema-org",),
        _classes,
    ),
    Artifact(
        "cff-1.2.0.schema.json",
        ("citation-file-format",),
        lambda d: d["citation-file-format"].json,
    ),
    Artifact(
        "biotools.schema.json",
        ("biotools-tool-type",),
        lambda d: d["biotools-tool-type"].json,
    ),
    Artifact(
        "spdx-licenses.json",
        ("spdx-license-list",),
        lambda d: licenses.build_spdx_index(d["spdx-license-list"].json),
    ),
    Artifact(
        "vocabularies.json",
        ("repostatus", "biotools-tool-type"),
        lambda d: vocabularies.build_vocabularies(
            d["repostatus"].json, d["biotools-tool-type"].json
        ),
    ),
    Artifact(
        "codemeta-crosswalks.json",
        tuple(sorted(set(crosswalks.CROSSWALK_SOURCES.values()))),
        crosswalks.build_crosswalks,
    ),
    Artifact(
        "format-hints.json",
        ("r-licenses", "pep-753"),
        lambda d: hints.build_format_hints(d["r-licenses"].text, d["pep-753"].text),
    ),
)


def build_provenance(downloads: Downloads, retrieved: str) -> dict[str, Any]:
    """Record where each vendored file came from, inverted from :data:`ARTIFACTS`."""
    contributions: dict[str, list[str]] = {key: [] for key in SOURCES}
    for artifact in ARTIFACTS:
        for key in artifact.sources:
            contributions[key].append(artifact.name)

    sources = {}
    for key in sorted(SOURCES):
        source = SOURCES[key]
        version: Any = source.version
        # SPDX is the one upstream that dates its own releases; keeping that
        # is what lets a reader tell a refresh from an actual list revision.
        dated = {}
        if key == "spdx-license-list":
            document = downloads[key].json
            version = document.get("licenseListVersion", source.version)
            dated["releaseDate"] = document.get("releaseDate")
        sources[key] = {
            "url": source.url,
            "version": version,
            **dated,
            "retrieved": retrieved,
            "sha256": downloads[key].sha256,
            "files": contributions[key],
            "license": source.license,
        }

    return {
        "$comment": (
            "Generated by scripts/vendor_reference_data.py. Do not edit by "
            "hand; run the script instead."
        ),
        "sources": sources,
    }


def serialize(payload: Any) -> str:
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


def refresh(check: bool = False) -> int:
    """Rebuild the vendored data, or report whether it is stale.

    Parameters
    ----------
    check : bool
        Report staleness and write nothing. Intended for a scheduled CI job.

    Returns
    -------
    int
        A process exit status: non-zero only when ``check`` found stale data.
    """
    downloads = fetch_all()
    built = {artifact.name: artifact.build(downloads) for artifact in ARTIFACTS}

    if check:
        stale = [
            name
            for name, payload in built.items()
            if not (DATA_DIR / name).exists()
            or (DATA_DIR / name).read_text("utf-8") != serialize(payload)
        ]
        if stale:
            print("\nStale vendored data:", ", ".join(sorted(stale)), file=sys.stderr)
            print(
                "Run: poetry run python scripts/vendor_reference_data.py",
                file=sys.stderr,
            )
            return 1
        print("\nVendored reference data is up to date.")
        return 0

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    for name, payload in built.items():
        (DATA_DIR / name).write_text(serialize(payload), "utf-8")
        print(f"  wrote {name}")
    provenance = build_provenance(downloads, dt.date.today().isoformat())
    (DATA_DIR / "provenance.json").write_text(serialize(provenance), "utf-8")
    print("  wrote provenance.json")
    return 0
