"""Parsers for the per-ecosystem conventions the adapters need.

These are not vocabularies. They are the small facts about how one packaging
ecosystem writes something down: which license strings CRAN accepts, which
`[project.urls]` labels Python treats as well known. Each ecosystem publishes
its own, so each is read from there.
"""

from __future__ import annotations

import re
from typing import Any

from .sources import SOURCES


def parse_r_licenses(text: str) -> dict[str, str]:
    """CRAN license strings mapped to SPDX identifiers, from R's license database.

    The database is a series of blank-line-separated records. ``SSS`` is the
    short string CRAN accepts in a ``DESCRIPTION``; ``SPDX`` is the identifier
    it corresponds to. Records without an SPDX identifier describe licenses
    SPDX has no entry for and are skipped.
    """
    records: list[dict[str, str]] = []
    current: dict[str, str] = {}
    for line in text.splitlines():
        if not line.strip():
            if current:
                records.append(current)
                current = {}
            continue
        key, _, value = line.partition(":")
        current[key.strip()] = value.strip()
    if current:
        records.append(current)

    mapping: dict[str, str] = {}
    for record in records:
        spdx = record.get("SPDX")
        if not spdx:
            continue
        version = record.get("Version", "")
        written = [
            value
            for value in (record.get("SSS"), record.get("Abbrev"), record.get("Name"))
            if value
        ]
        # CRAN accepts the name and the version written together, which is how
        # "Apache License 2.0" appears in a DESCRIPTION.
        if version:
            written += [f"{value} {version}" for value in written]
        for value in written:
            mapping.setdefault(value.casefold(), spdx)
    return dict(sorted(mapping.items()))


def parse_pep_url_labels(text: str) -> dict[str, list[str]]:
    """Well-known ``[project.urls]`` labels and their aliases, from PEP 753.

    Returns
    -------
    dict
        Normalized label mapped to the aliases PEP 753 lists for it, the label
        itself included. Comparison is done after the PEP's own normalization:
        case-folded, with non-alphanumerics removed.
    """
    block = text[text.index("Well-known labels") :]
    rows: list[list[str]] = []
    current: list[str] = []
    for line in block.splitlines():
        stripped = line.strip()
        if stripped.startswith("* - "):
            if current:
                rows.append(current)
            current = [stripped[4:]]
        elif stripped.startswith("- ") and current:
            current.append(stripped[2:])
        elif stripped.startswith(".. ") and current:
            break
    if current:
        rows.append(current)

    labels: dict[str, list[str]] = {}
    for row in rows:
        if len(row) < 3:
            continue
        names = re.findall(r"``([^`]+)``", row[0])
        if not names:
            continue
        aliases = re.findall(r"``([^`]+)``", row[2])
        labels[names[0]] = sorted({names[0], *aliases})
    if not labels:
        raise ValueError("PEP 753's well-known label table could not be parsed")
    return labels


def build_format_hints(r_license_db: str, pep_labels: str) -> dict[str, Any]:
    """How other ecosystems spell things, fetched from each ecosystem.

    Both halves used to be transcribed. R publishes the license mapping in the
    same database ``tools::analyze_license`` reads, and PEP 753 publishes the
    well-known URL labels, so neither needs to be maintained here.
    """
    return {
        "$comment": (
            "Generated by scripts/vendor_reference_data.py from each "
            "ecosystem's own published source."
        ),
        "rLicenseAliases": {
            "$comment": (
                "CRAN license strings mapped to SPDX identifiers, from R's "
                "share/licenses/license.db. CRAN's expression grammar — "
                "'GPL (>= 2)' meaning or-later, '|' meaning or — is parsing "
                "rather than vocabulary and lives in the R adapter."
            ),
            "source": SOURCES["r-licenses"].url,
            "aliases": parse_r_licenses(r_license_db),
        },
        "pyprojectUrlRoles": {
            "$comment": (
                "Well-known [project.urls] labels and their aliases, from PEP "
                "753. Comparison uses the PEP's own normalization: case-folded "
                "with non-alphanumerics removed, which is also what makes "
                "Poetry's spellings match."
            ),
            "source": SOURCES["pep-753"].url,
            "labels": parse_pep_url_labels(pep_labels),
        },
    }
